// Generated by CoffeeScript 1.6.3
(function() {
  this.Common = (function() {
    /*
    Global varaiables
    */

    var PROXY, URL;

    function Common() {}

    PROXY = "";

    URL = "http://www.obd-memorial.ru/tails/tail200k.txt?";

    Common.prototype.FULL_URL = PROXY + URL + Math.random();

    Common.prototype.getFullUrl = function() {
      return PROXY + URL + Math.random();
    };

    Common.prototype.setUrl = function(url) {
      return URL = url;
    };

    /*
    Common functions
    */


    /*
    padding the string s with spaces
    s - the string to pad
    L - total length
    */


    Common.prototype.toStr = function(s, L) {
      var len, sh, ss;
      ss = "" + s;
      sh = "                                        ";
      len = ss.length;
      if (L < len) {
        return ss.substr(0, L);
      } else {
        return sh.substr(0, L - len) + ss;
      }
    };

    Common.prototype.getCurrentTime = function() {
      var d;
      d = new Date();
      return "" + (d.getHours()) + ":" + (d.getMinutes()) + ":" + (d.getSeconds()) + "." + (d.getMilliseconds());
    };

    Common.prototype.getCurrentSec = function() {
      var d;
      d = new Date();
      return 3600 * d.getHours() + 60 * d.getMinutes() + d.getSeconds() + 0.001 * d.getMilliseconds();
    };

    return Common;

  })();

}).call(this);

/*
//@ sourceMappingURL=common.map
*/
