// Generated by CoffeeScript 1.6.3
(function() {
  this.Common = (function() {
    /*
    Global varaiables
    */

    var PROXY, URL;

    function Common() {}

    PROXY = "";

    URL = "http://172.16.57.226/tails/tail200k.txt?";

    Common.prototype.FULL_URL = PROXY + URL + Math.random();

    /*
    Common functions
    */


    /*
    padding the string s with spaces
    s - the string to pad
    L - total length
    */


    Common.prototype.toStr = function(s, L) {
      var len, sh, ss;
      ss = "" + s;
      sh = "                                        ";
      len = ss.length;
      if (L < len) {
        return ss.substr(0, L);
      } else {
        return sh.substr(0, L - len) + ss;
      }
    };

    return Common;

  })();

}).call(this);

/*
//@ sourceMappingURL=common.map
*/
