// Generated by CoffeeScript 1.6.3
(function() {
  this.Drops = (function() {
    var desk, i, lin, outerContainer, particle, svg, z;

    svg = null;

    desk = null;

    outerContainer = null;

    z = d3.scale.category20c();

    i = 0;

    lin = function(x) {
      return x;
    };

    particle = function(logRecord) {
      var fillColor, h, rand, w, xx, yy;
      w = outerContainer.width();
      h = outerContainer.height();
      xx = w * Math.random();
      rand = Math.random();
      yy = h * rand * 0.1 + h / 2;
      fillColor = logRecord.method === '"POST' ? "#0FF" : "white";
      if (logRecord.image) {
        fillColor = "red";
      }
      return svg.append("svg:circle").attr("cx", xx - 100).attr("cy", yy - 200).attr("r", 2).style("fill", fillColor).style("fill-opacity", 0.1).transition().duration(500).ease("linear").attr("cy", yy).attr("cx", xx).style("fill-opacity", 0.1 + rand).remove().each("end", function() {
        var r;
        r = 10 + 80 * rand;
        if (typeof console !== "undefined" && console !== null) {
          console.log("method=" + logRecord.method + " " + logRecord.line);
        }
        svg.append("svg:ellipse").attr("cx", xx).attr("cy", yy).attr("rx", 1).attr("ry", 1 * 0.2).style("fill", logRecord.success ? fillColor : "black").style("fill-opacity", 0.1 + rand).style("stroke", "white").style("stroke-opacity", 0).style("stroke-width", 1).transition().duration(3000).ease(Math.sqrt).ease("linear").attr("rx", r).attr("ry", r * 0.2).style("stroke-width", 1 + 2 * rand).style("stroke-opacity", 1e-6).style("fill-opacity", 1e-6).remove();
        return svg.append("svg:circle").attr("cx", xx).attr("cy", yy).attr("r", 4).style("fill", fillColor).style("fill-opacity", 0.1 + rand).transition().duration(1000).ease(Math.sqrt).attr("cy", logRecord.success ? yy - 200 : yy + 200).attr("cx", xx + 100).style("fill-opacity", 0.1).attr("r", 4).remove();
      });
    };

    Drops.prototype.clear = function() {
      return desk.html("");
    };

    Drops.prototype.write = function(text) {
      return desk.html(desk.html() + text);
    };

    Drops.prototype.show = function(log, startTime, period) {
      var rec, records, _i, _len, _results;
      if (startTime == null) {
        startTime = 10;
      }
      if (period == null) {
        period = 0.5;
      }
      if (!log) {
        return;
      }
      records = log.getPastRecords2(startTime, period);
      _results = [];
      for (_i = 0, _len = records.length; _i < _len; _i++) {
        rec = records[_i];
        _results.push(particle(rec));
      }
      return _results;
    };

    function Drops(containerSelector) {
      outerContainer = $(containerSelector);
      svg = d3.select("#dropSvg");
    }

    return Drops;

  })();

}).call(this);

/*
//@ sourceMappingURL=Drops.map
*/
