// Generated by CoffeeScript 1.6.3
(function() {
  var LOG, drops, shortSpan, startTime, summary, timer, timerPeriod, updatePeriod, updater;

  this.GLOB = new Common;

  LOG = null;

  updatePeriod = 5000;

  timerPeriod = 100;

  startTime = 10;

  updater = null;

  summary = null;

  shortSpan = null;

  drops = null;

  timer = new Timer;

  timer.setCallback(function() {
    shortSpan.show(LOG, startTime, 0.001 * timerPeriod);
    drops.show(LOG, startTime, 0.001 * timerPeriod);
    return null;
  });

  $(function() {
    updater = new LogUpdater();
    summary = new LogSummary("#summaryContainer");
    shortSpan = new ShortSpan("#shortSpanContainer");
    drops = new Drops("#dropContainer");
    updater.init();
    updater.onUpdate(function(log) {
      LOG = log;
      return summary.show(LOG);
    });
    $("#btnStart0").click(function() {
      return updater.start(updatePeriod);
    });
    $("#btnStop0").click(function() {
      return updater.stop();
    });
    $("#btnStart1").click(function() {
      return timer.start(timerPeriod);
    });
    $("#btnStop1").click(function() {
      return timer.stop();
    });
    $("#sldFreq").change(function() {
      var fr;
      fr = $("#sldFreq").val();
      timerPeriod = 1000.0 / fr;
      timer.stop();
      return timer.start(timerPeriod);
    });
    return $("#selectUrl").change(function() {
      GLOB.setUrl($("#selectUrl").val());
      updater.stop();
      return updater.start(updatePeriod);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
