// Generated by CoffeeScript 1.6.3
(function() {
  this.LogSummary = (function() {
    var desk, outerContainer;

    desk = null;

    outerContainer = null;

    LogSummary.prototype.clear = function() {
      return desk.html("");
    };

    LogSummary.prototype.write = function(text) {
      return desk.html(desk.html() + text);
    };

    LogSummary.prototype.show = function(log) {
      var error;
      this.clear();
      try {
        return this.write("<pre>\nS U M M A R Y\n--------------------------\n" + (log.count()) + " Requests / " + (log.getTimeLength().toFixed(2)) + "  sec\nRequests Per Second " + (log.getRecordsPerSecond().toFixed(2)) + "\n</pre>");
      } catch (_error) {
        error = _error;
        return this.write("                    <pre style='font-size:20px; color:red'>                    -----------------------                    " + (error.toString()) + "                    -----------------------                    </pre>                    ");
      }
    };

    function LogSummary(containerSelector) {
      desk = $(containerSelector);
    }

    return LogSummary;

  })();

}).call(this);

/*
//@ sourceMappingURL=LogSummary.map
*/
