// Generated by CoffeeScript 1.6.3
(function() {
  this.ShortSpan = (function() {
    var desk, outerContainer;

    desk = null;

    outerContainer = null;

    ShortSpan.prototype.clear = function() {
      return desk.html("");
    };

    ShortSpan.prototype.write = function(text) {
      return desk.html(desk.html() + text);
    };

    ShortSpan.prototype.show = function(log, startTime, period) {
      var toTheEnd;
      if (startTime == null) {
        startTime = 10;
      }
      if (period == null) {
        period = 0.5;
      }
      if (!log) {
        return;
      }
      this.clear();
      toTheEnd = (log.getLastTimeSec() - (GLOB.getCurrentSec() - startTime)).toFixed(2);
      return this.write("<h4>Short time span</h4>\n<pre>\nCurrent Time: " + (log.getCurrentTime()) + " " + (log.getCurrentSec()) + "\nStart time: " + startTime + " Period: " + (period.toFixed(3)) + " Frequency: " + (Math.round(1 / period)) + "\nTime to the the end of log: " + toTheEnd + " seconds\n-----------------------\n" + (log.getPastRecords(startTime, period).join('\n')) + "\n</pre>");
    };

    function ShortSpan(containerSelector) {
      outerContainer = $(containerSelector);
      desk = $("#outputArea");
    }

    return ShortSpan;

  })();

}).call(this);

/*
//@ sourceMappingURL=ShortSpan.map
*/
