// Generated by CoffeeScript 1.6.3
(function() {
  var Visualizer0;

  Visualizer0 = (function() {
    var area, clear, getSummary, out, timer, updateArea, write;

    function Visualizer0() {}

    area = null;

    out = null;

    timer = null;

    Visualizer0.myLog = null;

    clear = function() {
      return area != null ? area.html("") : void 0;
    };

    write = function(text) {
      return area.html(area.html() + text);
    };

    Visualizer0.prototype.stop = function() {
      clearInterval(timer);
      return clear();
    };

    Visualizer0.prototype.start = function() {
      this.stop();
      getSummary();
      return timer = setInterval(getSummary, 5000);
    };

    updateArea = function() {
      clear();
      write(this.myLog.getSummary());
      return write("<pre>\n" + (myLog.getCurrentTime()) + " ************************\n" + (myLog.getPastRecords(10, 0.5).join("\n")) + "\n" + (myLog.getCurrentTime()) + " ************************\n--------------------------\n{myLog.getShortLog()}\n</pre>");
    };

    getSummary = function() {
      var _this = this;
      this.myLog = new ApacheLog();
      return $.get(Common.FULL_URL, function(txt) {
        _this.myLog.addText(txt);
        return updateArea();
      });
    };

    Visualizer0.prototype.init = function() {
      clearInterval(timer);
      this.myLog = new ApacheLog();
      out = $("#out2");
      out.html("");
      area = $("<div style='position:relative; left:0px; top:0px;  width:550px; height:600px; border:1px solid silver; color:black; overflow-y:hidden;'>mmm<div>");
      return out.append(area);
    };

    return Visualizer0;

  })();

}).call(this);

/*
//@ sourceMappingURL=Visualizer0.map
*/
